# Generated by Django 4.0.4 on 2022-04-30 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_location_user_locations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='firsrt_name',
            new_name='first_name',
        ),
    ]
