# Generated by Django 4.0.4 on 2022-04-23 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='address',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ad',
            name='is_published',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
