# Generated by Django 4.0.4 on 2022-04-23 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_ad_address_ad_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='description',
            field=models.CharField(max_length=1500),
        ),
    ]
